development:
  adapter: postgresql
  database: randoms_dev
  username: kangmo
  password: stageit123
  encoding: utf8
  host: localhost
  pool: 5

 production:
  adapter: postgresql
  database: randoms_dev
  username: kangmo
  password: stageit123
  encoding: utf8
  host: localhost
  pool: 5