randoms.scattergoriesCategoryLists = [
		["video games",
			"electronic gadgets",
			"board games",
			"things that use a remote",
			"card games",
			"internet lingo",
			"offensive words",
			"wireless things",
			"computer parts",
			"software",
			"websites",
			"game terms"
		],
		["things in a grocery store",
			"reasons to quit your job",
			"things that have stripes",
			"tourist attractions",
			"diet foods",
			"things found in a hospital",
			"food/drink that is green",
			"weekend activities",
			"acronyms",
			"seafood",
			"christmas songs",
			"words ending in '-N'"
		],
		["words with double letters"
			"children's books"
			"things found at a boardsports played indoors"
			"names used in songs"
			"foods you eat raw"
			"places in europe",
			"olympic events",
			"things you see at the zoo",
			"math terms",
			"animals in books or movies",
			"things to do at a party"
		],
		["kinds of soup",
			"things found in new york",
			"things you get tickets for ",
			"things you do at work",
			"foreign words used in english",
			"thigns you shouldn't touch",
			"spicy foods",
			"things at a carnival",
			"things you make",
			"places to hang out",
			"animal noises",
			"computer programs"
		],
		["sandwiches",
			"items in a catalog",
			"world leaders/politicans",
			"school subjects",
			"excuses for being late",
			"ice cream flavors",
			"things that jump/bounce",
			"television stars",
			"things in a park",
			"foreign cities",
			"stones/gems",
			"musical instruments"
		],	
		["fictional characters",
			"menu items",
			"magazines",
			"capitals",
			"kinds of candy",
			"items you save up to buy",
			"footware",
			"something you keep hidden",
			"items in a suitcase",
			"things with tails",
			"sports equipment",
			"crimes"
		],
		["things that are sticky",
			"awards/ceremonies",
			"cars",
			"spices/herbs",
			"bad habits",
			"cosmetics/toiletries",
			"celebrities",
			"cooking utensils",
			"reptiles/amphibians",
			"parks",
			"leisure activities",
			"things you're allergic to"
		],
		["restaurants",
			"notorious people",
			"fruits",
			"things in a medicine cabinet",
			"toys",
			"household chores",
			"bodies of water",
			"authors",
			"halloween costumes",
			"weapons",
			"things that are dead",
			"words associated with exercises"
		]

	]